version: "3.9"
services:
  postgres:
    image: pg-job-parser:local
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "pgtest"
      POSTGRES_PASSWORD: "pgtest"
    volumes:
      - ../../src/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
